# Generated by Django 4.2.5 on 2023-10-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_text_articles_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_time_comment',
            new_name='date_time_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_comment',
            field=models.CharField(max_length=1000),
        ),
    ]
